authentication/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, CustomPasswordChangeView, ForgotPasswordView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
]

chat/urls.py
from django.urls import path, include
from chat import views 
from django.urls import re_path

urlpatterns = [
    path("index/", views.index, name="inbox"),
    path("inbox/<int:user_id>/", views.inbox_detail, name="inbox_detail"),
    path("inbox-room/<int:room_id>/", views.inbox_group_detail, name="inbox_room_detail"),
    path("create-room/", views.CreateChatRoom.as_view(), name="create_room"),
    path("delete-room/<int:room_id>/", views.DeleteChatRoom.as_view(), name="delete_room"),
    path("edit-room/<int:room_id>/", views.EditChatRoom.as_view(), name="edit_room"),
    path("add-member-room/<int:room_id>/<int:user_id>/", views.AddMembersRoomChat.as_view(), name="add_member_room"),
    path("delete-member-room/<int:room_id>/<int:user_id>/", views.DeleteMembersRoomChat.as_view(), name="delete_member_room"),
    path("delete-private-chat/<int:user_id>/", views.DeletePrivateChat.as_view(), name="delete_private_chat"),

]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('profiles/', include('profiles.urls')),
    path('social/', include('social.urls')),
    path("chat/", include("chat.urls")),
    path('', include('posts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
# models.py trong ứng dụng authentication
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="custom_user_set",
        related_query_name="user",
    )

class OTP(models.Model):
    code = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='otps', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False)
    
    def getCode(self):
        return self.code

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from .models import User, OTP

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']
        # Vô hiệu hóa xác nhận mật khẩu
        password_confirmation_required = False
        # Vô hiệu hóa kiểm tra độ mạnh mật khẩu
        password_validators = []


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ChangePasswordForm(PasswordChangeForm):

    class Meta:
        model = User
        fields = ['old_password','new_password1','new_password2']

class ForgotPasswordForm(forms.ModelForm):
    otp = forms.CharField(max_length=6, label='OTP', required=False)
    class Meta:
        model = User
        fields = ['email', 'otp']

authentication/views.py
# authentication/views.py
from django.views.generic import CreateView, View
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q

from django.core.mail import send_mail
from django.http import HttpResponse

from socialmedia.settings import EMAIL_HOST_USER
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomAuthenticationForm, ChangePasswordForm, ForgotPasswordForm
from .models import OTP, User
from profiles.models import Profile

import random
import string

# đăng kí 
class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'authentication/register.html'

    def form_valid(self, form):
        response = super().form_valid(form)  # This will create the user
        profile_pic_path = 'cover_photos/logotdc.jpg'  # Replace with the actual path to your static image
        Profile.objects.create(user=self.object, profile_pic=profile_pic_path)  #
        return response  # Return the response object to continue the no

class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Tên đăng nhập hoặc mật khẩu không đúng.",
        # Các thông báo lỗi khác nếu cần
    }

# đăng nhập
class LoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'authentication/login.html'
    def form_invalid(self, form):
        messages.error(self.request, form.error_messages['invalid_login'])
        return super().form_invalid(form)
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.get_user()
        if user.is_authenticated:
            context = {
                'user': user,
            }            
            return redirect('home')  
        return super().form_valid(form)

# đổi mật khẩu
@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class CustomPasswordChangeView(PasswordChangeView):
    form_class = ChangePasswordForm    
    template_name = 'authentication/password_reset.html' 
    success_url = reverse_lazy('home')
    

# quên mật khẩu
class ForgotPasswordView(View):
    form_class = ForgotPasswordForm
    template_name = 'authentication/forgot_password.html' 

    def get(self, request):
        form = ForgotPasswordForm()
        return render(request, self.template_name, { 'form': form, 'check_email': True, 'check_otp': True })

    def post(self, request):
        form = ForgotPasswordForm(request.POST)
        first_filter = Q(email=request.POST.get('email'))
        second_filter = Q(email=request.session.get('email'))
        user = User.objects.filter(first_filter | second_filter).first()
        print(user)

        if not user:
            return render(request, self.template_name, { 'form': form, 'check_email': False, 'check_otp': True })
        elif 'send-otp' in request.POST:
            rs_form = ForgotPasswordForm(request.POST, initial={'email': request.POST.get('email')})
            if not request.session.get('email'):
                request.session['email'] = request.POST.get('email')
            code = random.randint(100000, 999999)
            OTP.objects.create(user=user, code=code, is_active=True)

            subject = 'Django social - OTP reset password'
            message = f'Your OTP is: {code}'
            from_email = EMAIL_HOST_USER
            recipient_list = [user.email]
            send_mail(subject, message, from_email, recipient_list)

            return render(request, self.template_name, { 'form': rs_form, 'email': request.POST.get('email') or request.session.get('email'), 'check_email': True, 'check_otp': True })
        else:
            otp = OTP.objects.filter(Q(is_active=True, user=user)).last()
            if otp.code == request.POST.get('otp'):
                print(f"otp is: {otp.code}", user.password)
                new_password = random_password()
                user.set_password(new_password)
                user.save()
                return render(request, self.template_name, { 
                    'form': form, 
                    'email': request.session.get('email'), 
                    'otp': otp.code,
                    'newpassword': new_password,
                    'check_email': True,
                    'check_otp': True
                })
            otp.is_active = False
            otp.save()
            return render(request, self.template_name, { 'form': form, 'email': request.session.get('email'), 'check_email': True, 'check_otp': False })

# Send mail
def random_password(length=20):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))

    return password

authentication/templates/authentication/forgot_password.html
{% extends 'base_generic.html' %}

{% block user %}
<div class="login-area">
  <div class="wrapper text-center">
    <div class="title text-uppercase text-center">Quên mật khẩu</div>
    <hr>
    <form class="form-login d-flex flex-column justify-content-center align-items-center" method="post">
      {% csrf_token %}
      <input type="text" name="email" autofocus="" autocapitalize="none" autocomplete="email" maxlength="150" required="" id="id_email" placeholder="Email" {% if email %}disabled{% endif %} value="{{ email|default:'' }}">
      {% if check_email == False %}
      <span class="check-invalid">Email không tồn tại</span>
      {% endif %}
      <div class="otp-area">
        <input type="text" name="otp" maxlength="6" id="id_otp" placeholder="Mã OTP" style="min-width: 250px;" value="{{ otp|default:'' }}">
        <button type="submit" name="send-otp" class="btn-login" style="min-width: 140px;">Gửi mã OTP</button>
      </div>
      {% if check_otp == False %}
      <span class="check-invalid">Mã OTP không chính xác</span>
      {% endif %}
      {% if newpassword %}
      <div class="new-password">
        <span style="min-width: 140px; display: inline-block;">Mật khẩu mới:</span>
        <input type="text" name="new-password" disabled value="{{ newpassword }}" style="min-width: 250px;">
      </div>
      {% endif %}
      <button type="submit" name="submit-form" class="btn-login">Xác nhận</button>
    </form>
    <hr>
    <a href="{% url 'login' %}" class="btn-register">Đăng nhập</a>
  </div>
</div>

{% endblock %}

authentication/templates/authentication/login.html
{% extends 'base_generic.html' %}

{% block user %}

<div class="login-area">
  <div class="wrapper text-center">
    <div class="title text-uppercase text-center">Đăng nhập</div>
    <hr>
    <form class="form-login d-flex flex-column justify-content-center align-items-center" method="post">
      {% csrf_token %}
      <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" placeholder="Tên đăng nhập">
      <input type="password" name="password" autocomplete="current-password" required="" id="id_password" placeholder="Mật khẩu">
      <button type="submit" class="btn-login">Đăng nhập</button>
      {% if messages %}
        <ul class="errorlist py-2">
          {% for message in messages %}
            <li style="color: red;">{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      <a class="forgot-password text-primary" href="{% url 'forgot_password' %}">Quên mật khẩu?</a>
    </form>
    <hr>
    <a href="{% url 'register' %}" class="btn-register">Tạo tài khoản mới</a>
  </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends 'base_generic.html' %}

{% block user %}
<div class="register-area">
    <div class="wrapper text-left">
        <div class="title text-uppercase text-center">Đổi mật khẩu</div>
        <hr>
        <form class="form-register d-flex flex-column justify-content-start align-items-center" method="post" action="{% url 'change_password' %}">
            {% csrf_token %}
            <label for="id_old_password">Mật khẩu cũ:</label>
            <input type="password" name="old_password" autocomplete="current-password" autofocus required id="id_old_password" placeholder="Nhập mật khẩu cũ">      
      
            <input type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1" placeholder="Nhập mật khẩu mới">
            <span class="help-text">
                <ul>
                    <li>Mật khẩu của bạn không được quá giống với thông tin cá nhân khác của bạn.</li>
                    <li>Mật khẩu của bạn phải chứa ít nhất 8 ký tự.</li>
                    <li>Mật khẩu của bạn không được là mật khẩu được sử dụng phổ biến.</li>
                    <li>Mật khẩu của bạn không được toàn là số.</li>
                </ul>
            </span>
            <input type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2" placeholder="Nhập lại mật khẩu mới">
            <button type="submit" class="btn-primary">Đổi mật khẩu</button>
        </form>s
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/register.html
{% extends 'base_generic.html' %}

{% block user %}

<div class="register-area">
  <div class="wrapper text-center">
    <div class="title text-uppercase text-center">register</div>
    <hr>
    <form class="form-register d-flex flex-column justify-content-center align-items-center" method="post">
      {% csrf_token %}
      <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="Tên đăng nhập">
      <input type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="Mật khẩu">
      <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Nhập lại mật khẩu">
      <input type="email" name="email" maxlength="254" id="id_email" placeholder="Email">
      <div class="btn-navigate d-flex justify-content-between align-items-center w-100">
        <button type="submit" class="btn-register">Đăng ký</button>
        <a href="{% url 'login' %}" class="btn-login">Đăng nhập</a>
      </div>
    </form>
  </div>
</div>

{% endblock %}