chat/urls.py
from django.urls import path, include
from chat import views 
from django.urls import re_path

urlpatterns = [
    path("index/", views.index, name="inbox"),
    path("inbox/<int:user_id>/", views.inbox_detail, name="inbox_detail"),
    path("inbox-room/<int:room_id>/", views.inbox_group_detail, name="inbox_room_detail"),
    path("create-room/", views.CreateChatRoom.as_view(), name="create_room"),
    path("delete-room/<int:room_id>/", views.DeleteChatRoom.as_view(), name="delete_room"),
    path("edit-room/<int:room_id>/", views.EditChatRoom.as_view(), name="edit_room"),
    path("add-member-room/<int:room_id>/<int:user_id>/", views.AddMembersRoomChat.as_view(), name="add_member_room"),
    path("delete-member-room/<int:room_id>/<int:user_id>/", views.DeleteMembersRoomChat.as_view(), name="delete_member_room"),
    path("delete-private-chat/<int:user_id>/", views.DeletePrivateChat.as_view(), name="delete_private_chat"),

]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('profiles/', include('profiles.urls')),
    path('social/', include('social.urls')),
    path("chat/", include("chat.urls")),
    path('', include('posts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from authentication.models import User
from django.contrib.auth import get_user_model


User = get_user_model()
class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="chat_user")
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="reciever")
    message = models.CharField(max_length=10000000000)
    image = models.ImageField(upload_to='room-messages/images/', blank=True, null=True)
    video = models.FileField(upload_to='room-messages/videos/', blank=True, null=True)
    is_read = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):        
        return f"Sender: {str(self.sender)} - receiver: {str(self.receiver)}"
    
    class Meta:
        ordering = ["-date"]
        verbose_name_plural = "Personal Chat"

class ChatRoom (models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='room-messages/cover-pic/', blank=True, null=True)
    creator = models.ForeignKey(User, max_length=255, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name="group_chat_members")
    def __str__(self):        
        return f"room: {str(self.name)} "
    

class RoomMessage(models.Model):
    room = models.ForeignKey(ChatRoom, on_delete= models.CASCADE)    
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="group_sender")
    message = models.CharField(max_length=1000)    
    image = models.ImageField(upload_to='messages/images/', blank=True, null=True)
    video = models.FileField(upload_to='messages/videos/', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Group: {self.room.name} - Sender: {self.sender.username}"

    class Meta:
        ordering = ["-date"]
        verbose_name_plural = "Group Chats"

chat/forms.py
from django import forms
from .models import ChatRoom

class ChatRoomForm(forms.ModelForm):
    class Meta:
        model = ChatRoom
        fields = ['name','image']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder' : 'Nhập tên phòng' }),
        }

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect

from django.views.generic import CreateView, View
from django.db.models import OuterRef, Subquery, Q
from .forms import ChatRoomForm
from .models import ChatMessage, ChatRoom, RoomMessage
from authentication.models import User
from profiles.models import Profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@login_required(login_url='/auth/login/')
def index(request):
    all_profiles = Profile.objects.all()

    chat_users = ChatMessage.objects.filter(Q(sender=request.user) | Q(receiver=request.user))
    list_user = list(set([chat.sender if chat.sender != request.user else chat.receiver for chat in chat_users]))
    list_room = ChatRoom.objects.filter(Q(members=request.user)| Q(creator=request.user)).distinct()
    combined_list = []

    # Thêm các người dùng vào danh sách kết hợp và đánh dấu chúng là người dùng
    for user in list_user:
        combined_list.append({'object': user, 'type': 'user'})

    # Thêm các phòng chat vào danh sách kết hợp và đánh dấu chúng là phòng chat
    for room in list_room:
        combined_list.append({'object': room, 'type': 'room'})
    context = {            
            "combined_list":combined_list,
            "profiles":all_profiles,
        }
    return render(request, 'chat/inbox.html', context)

@login_required(login_url='/auth/login/')
def inbox_detail(request, user_id):

    sender = request.user
    receiver_user = User.objects.get(id =user_id)
    message_list = ChatMessage.objects.filter(
        Q(sender=sender, receiver=receiver_user) | Q(sender=receiver_user, receiver=sender)
    ).order_by("date")

    messages_detail = ChatMessage.objects.filter(
        Q(sender=sender, receiver=receiver_user) | Q(sender=receiver_user, receiver=sender)
    ).order_by("date")

    chat_users = ChatMessage.objects.filter(Q(sender=request.user) | Q(receiver=request.user))
    list_user = list(set([chat.sender if chat.sender != request.user else chat.receiver for chat in chat_users]))

    list_room = ChatRoom.objects.filter(Q(members=request.user)| Q(creator=request.user)).distinct()
    combined_list = []

    # Thêm các người dùng vào danh sách kết hợp và đánh dấu chúng là người dùng
    for user in list_user:
        combined_list.append({'object': user, 'type': 'user'})

    # Thêm các phòng chat vào danh sách kết hợp và đánh dấu chúng là phòng chat
    for room in list_room:
        combined_list.append({'object': room, 'type': 'room'})


    all_profiles = Profile.objects.all()

    if messages_detail:
        r = messages_detail.first()
        receiver = User.objects.get(username=r.receiver)
    else:
        receiver = User.objects.get(id =user_id)

    context = {
        "receiver":receiver,
        "receiver_user":receiver_user,
        "sender":sender,
        "message_list":message_list,
        "combined_list":combined_list,    
        "profiles":all_profiles,
    }
    return render(request, 'chat/inbox_detail.html', context)


@login_required(login_url='/auth/login/')
def inbox_group_detail(request, room_id):
    room_name = ChatRoom.objects.get(id = room_id)
    message_list = RoomMessage.objects.filter(
        Q(room__id = room_name.id)
    ).order_by("date")
    reversed_list = list(reversed(message_list))

    sender = request.user
   
    all_profiles = Profile.objects.all()

    chat_users = ChatMessage.objects.filter(Q(sender=request.user) | Q(receiver=request.user))
    list_user = list(set([chat.sender if chat.sender != request.user else chat.receiver for chat in chat_users]))
    list_room = ChatRoom.objects.filter(Q(members=request.user)| Q(creator=request.user)).distinct()
    combined_list = []

    # Thêm các người dùng vào danh sách kết hợp và đánh dấu chúng là người dùng
    for user in list_user:
        combined_list.append({'object': user, 'type': 'user'})

    # Thêm các phòng chat vào danh sách kết hợp và đánh dấu chúng là phòng chat
    for room in list_room:
        combined_list.append({'object': room, 'type': 'room'})

    friends = User.objects.filter(
                Q(friendships1__user2=request.user, friendships1__status='friends') |
                Q(friendships2__user1=request.user, friendships2__status='friends')
            ).distinct()

    # danh sách thành viên nhóm chat
    room_members = room_name.members.all().exclude(id = room_name.creator.id )
    # danh sách bạn bè chưa tham gia nhóm chat
    not_joined_friends = friends.exclude(id__in=[member.id for member in room_members])

    form = ChatRoomForm(request.GET, request.FILES, instance=room_name)

    context = {     
        "sender":sender,
        "message_list":message_list,
        "room": room_name,    
        "list_user":list_user,
        "list_room":list_room,
        "profiles":all_profiles,     
        "combined_list":combined_list,     
        "friends":friends,     
        "room_members":room_members,     
        "not_joined_friends":not_joined_friends,     
        "form":form,     
    }    
    return render(request, 'chat/inbox_group.html', context)


@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class CreateChatRoom(CreateView):
    template_name = 'chat/inbox.html'
    def get(self, request):
        form = ChatRoomForm(request.POST, request.FILES)  # Tạo một mẫu trống để hiển thị
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ChatRoomForm(request.POST, request.FILES)  # Truyền dữ liệu từ POST và FILES vào mẫu
        if form.is_valid():
            chatroom = form.save(commit=False)  # Lưu nhóm vào cơ sở dữ liệu
            chatroom.creator = self.request.user
            chatroom.save()
            return redirect('inbox_room_detail', room_id=chatroom.id)  # Chuyển hướng đến trang bài viết của nhóm vừa tạo

        return redirect('inbox_room_detail', room_id=chatroom.id)
    

@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class DeleteChatRoom(View):
    def post(self, request, room_id):
        room = get_object_or_404(ChatRoom, id=room_id)
        if request.user.id == room.creator.id:
            room.delete()
        return redirect('inbox')  # Điều hướng sau khi xóa

    def get(self, request, room_id):
        room = get_object_or_404(ChatRoom, id=room_id)
        if request.user.id == room.creator.id:
            room.delete()
        return redirect('inbox')
    
@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class EditChatRoom(View):
    template_name = 'chat/inbox_group.html'

    def post(self, request, room_id):
        room = get_object_or_404(ChatRoom, id=room_id)
        print(1111)
        print(room.name)
        form = ChatRoomForm(request.POST, request.FILES, instance=room)
        if request.user == room.creator:
            if form.is_valid():
                form.save()
            return redirect('inbox_room_detail',room_id=room_id)  # Điều hướng sau khi xóa
    
        return render(request, self.template_name, {'form': form, 'room_id': room_id})

@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class AddMembersRoomChat(CreateView):
    def post(self, request, user_id, room_id):
        room = get_object_or_404(ChatRoom, id=room_id)
        if request.user.id == room.creator.id:
            user = get_object_or_404(User, id = user_id)
            if not user in room.members.all():
                room.members.add(user)
            return redirect('inbox_room_detail', room_id=room_id)
        return redirect('inbox_room_detail', room_id=room_id)
        

@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class DeleteMembersRoomChat(View):
    def post(self, request, user_id, room_id):
        room = get_object_or_404(ChatMessage, id=room_id)
        user = get_object_or_404(User,id=user_id)
        if request.user.id == room.creator.id :        
            if user in room.members.all():
                room.members.remove(user)
            return redirect('inbox_room_detail', room_id=room_id)
        if request.user == user:
            if user in room.members.all():
                room.members.remove(user)
            return redirect('inbox')
        return redirect('inbox_room_detail', room_id=room_id)
    
@method_decorator(login_required(login_url='/auth/login/'), name='dispatch')
class DeletePrivateChat(View):
    def post(self, request, user_id):
        receiver = get_object_or_404(User,id=user_id)
        sender = request.user  # Thay bằng người gửi cụ thể

        # Lấy tất cả các tin nhắn liên quan đến người gửi và người nhận
        messages_to_delete = ChatMessage.objects.filter(sender=sender, receiver=receiver) | ChatMessage.objects.filter(sender=receiver, receiver=sender)

        # Kiểm tra xem có tin nhắn nào để xóa hay không
        if messages_to_delete.exists():
            # Xóa tất cả các tin nhắn
            messages_to_delete.delete()
            # Tin nhắn đã được xóa thành công
            return redirect('inbox')
        else:
            messages_to_delete.delete()
            # Không có tin nhắn nào để xóa
            # Thực hiện logic hoặc trả về thông báo tùy thuộc vào yêu cầu của bạn
            return redirect('inbox')
        

chat/templates/chat/inbox.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />


<div class="content-chat" >
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="chat-app">
            <div id="plist" class="people-list ">
                <div class="input-group">                    
                    <a href="" class="func-item w-100 p-3" data-bs-toggle="modal" data-bs-target="#example"> 
                        <i class="fa-solid fa-add"></i>
                        <span>Tạo Phòng chat</span>
                    </a>                    
                </div>
                <div class="list-user overflow-auto scroll-smooth">
                    <div class="d-block">
                        <ul class="list-unstyled chat-list mt-2 mb-0">
                            {% for user_item in combined_list %}
                                {% if user_item.type == "user"  %}
                                <a href="{% url 'inbox_detail' user_item.object.id %}">
                                    <li class="clearfix "  {% if user_item.object.username == receiver.username %} id="active" {% endif %}>
                                        {% for profile in profiles %}   
                                            {% if user_item.object == profile.user %}             
                                                <img src="{% if profile.profile_pic %}
                                                    {{ profile.profile_pic.url  }}
                                                {% else %} 
                                                    https://scontent.fsgn2-3.fna.fbcdn.net/v/t1.30497-1/143086968_2856368904622192_1959732218791162458_n.png?stp=cp0_dst-png_p60x60&_nc_cat=1&ccb=1-7&_nc_sid=2b6aad&_nc_eui2=AeE1vTPkHb-3caw-Qa8LcUBUso2H55p0AlGyjYfnmnQCUZJq8s60z2bWHjSCVInwd04OWKdpTROsfDIQw33wpZKQ&_nc_ohc=x-5IH6VdBkQAX973AOb&_nc_ht=scontent.fsgn2-3.fna&oh=00_AfDK83mRdv0PL08D0btIF9cOTS3s8hnIALTSupH9AKV5XQ&oe=657722F8
                                                {% endif %}" 
                                                alt="avatar">
                                            {% endif %}
                                        {% endfor %}
                                        <div class="about">
                                            <div class="name p-2" style="text-transform: capitalize;">{{user_item.object.username}}</div>
                                        </div>
                                    </li>
                                </a>
                                {% else %}
                                <a href="{% url 'inbox_room_detail' user_item.object.id %}">
                                    <li class="clearfix ">                                            
                                        {% if user_item.object.image %}             
                                            <img src="{{ user_item.object.image.url  }}" alt="avatar" style="width: 40px; " >
                                        {% else %}
                                            <img src="{% static 'room.png' %}" alt=""  style="width: 40px;">
                                        {% endif %}
                                        <div class="about">
                                            <div class="name p-2" style="text-transform: capitalize;">{{user_item.object.name}}</div>
                                        </div>
                                    </li>
                                </a>
                                {% endif %}
                            {% endfor %}                                
                        </ul>
                    </div>
                </div>
            </div>
        {% block room %}
        <div class="modal fade" id="example" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">Tạo phòng chat</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'create_room' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div href="" class="user">
                            <a href="" class="d-flex align-items-center justify-content-center">
                                {% for profile in profiles %}               
                                    {% if user.id == profile.user.id %}
                                        {% if profile.profile_pic %}
                                                <img src="{{ profile.profile_pic.url }}" style="width: 50px; height:50px" class="rounded-pill" alt="">
                                            {% else %}
                                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDJaEoQJ0PLbNOn_xHRIw7mcyuIOj0_hVZlA&usqp=CAU" style="width: 50px; height:50px" style="width: 40px; height:40px" alt="">
                                            {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </a>
                            <div class="author">
                                <div>Người tạo: {{ user.username }}</div>                                       
                            </div>
                        </div>
                        <div class="post-body mt-4">
                            <h3 class="post-title w-100 rounded">
                                <input class=" w-100 rounded form-control" type="text" name="name" required id="id_name" placeholder="Nhập tên phòng">
                            </h3>
                            
                        </div>
                    </div>                               
                    <div class="modal-footer d-flex justify-content-lg-center">                                    
                        <div class="p-2 rounded" style="position: relative; display: inline-block; width: 15%; background-color: var(--bg-light-3);">
                            <input class="btn-add-file" type="file" name="image" accept="image/*" id="id_image" style="align-self: center;opacity: 0; width: 100%; height: 100%; position: absolute; top: 0; left: 0; cursor: pointer;">
                            <div id="file-icon" class="text-center">                             
                                Ảnh
                            </div>
                        </div>             
                        <button type="submit" class="btn btn-primary btn-upload">Tạo phòng</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
        {% endblock %}
            <div class="chat">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                            </a>
                            <div class="chat-about">
                                <h6 class="m-b-0">Aiden Chavez</h6>
                                <small>Last seen: 2 hours ago</small>
                            </div>
                        </div>
                        <div class="col-lg-6 hidden-sm text-end">
                            <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
                        </div>
                    </div>
                </div>
                <div class="chat-history overflow-auto scroll-smooth">
                    <div class="d-block">
                    <ul class="m-b-0">
                        <li class="clearfix">
                            <div class="message-data text-end">
                                <span class="message-data-time">10:10 AM, Today</span>
                                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
                            </div>
                            <div class="message other-message float-right"> Hi Aiden, how are you? How is the project coming along? </div>
                        </li>
                        <li class="clearfix">
                            <div class="message-data text-start">
                                <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
                                <span class="message-data-time">10:12 AM, Today</span>
                            </div>
                            <div class="message my-message">Are we meeting today?</div>                                    
                        </li>                               
                        <li class="clearfix">
                            <div class="message-data text-start">
                                <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
                                <span class="message-data-time">10:12 AM, Today</span>
                            </div>
                            <div class="message my-message">Are we meeting today?</div>                                    
                        </li>                               
                        <li class="clearfix">
                            <div class="message-data text-start">
                                <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
                                <span class="message-data-time">10:12 AM, Today</span>
                            </div>
                            <div class="message my-message">Are we meeting today?</div>                                    
                        </li>                               
                        
                    </ul>
                </div>
            </div>
                <div class="chat-message clearfix">
                    <div class="input-group mb-0">
                        <div class="input-group-prepend" style="display: flex;">
                            <button class="input-group-text" style="margin: 5px; padding: 1rem;">
                                <i class="fa fa-image"></i>
                            </button>
                            <input type="text" class="form-control" id="chat-input" placeholder="Enter text here...">                                    
                            <button class="input-group-text" style="margin: 5px; padding: 1rem;" id="send-btn">
                               <i class="fa fa-send"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}