chat/urls.py
from django.urls import path, include
from chat import views 
from django.urls import re_path

urlpatterns = [
    path("index/", views.index, name="inbox"),
    path("inbox/<int:user_id>/", views.inbox_detail, name="inbox_detail"),
    path("inbox-room/<int:room_id>/", views.inbox_group_detail, name="inbox_room_detail"),
    path("create-room/", views.CreateChatRoom.as_view(), name="create_room"),
    path("delete-room/<int:room_id>/", views.DeleteChatRoom.as_view(), name="delete_room"),
    path("edit-room/<int:room_id>/", views.EditChatRoom.as_view(), name="edit_room"),
    path("add-member-room/<int:room_id>/<int:user_id>/", views.AddMembersRoomChat.as_view(), name="add_member_room"),
    path("delete-member-room/<int:room_id>/<int:user_id>/", views.DeleteMembersRoomChat.as_view(), name="delete_member_room"),
    path("delete-private-chat/<int:user_id>/", views.DeletePrivateChat.as_view(), name="delete_private_chat"),

]

profiles/urls.py
# profiles/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileCreateView, ProfileUpdateView, DeletePost, EditPostView, AddPostView

app_name = 'profiles'

urlpatterns = [
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),
    path('delete-post/<int:post_id>/', DeletePost.as_view(), name='delete_post'),
    path('edit-post/<int:post_id>/', EditPostView.as_view(), name='edit_post'),
    path('upload_post/', AddPostView.as_view(), name='upload_post'),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('profiles/', include('profiles.urls')),
    path('social/', include('social.urls')),
    path("chat/", include("chat.urls")),
    path('', include('posts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/error.html
<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bootstrap 5 404 Error Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>


    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The page you’re looking for doesn’t exist.
                  </p>
                <a href="{% url 'home' %}" class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </body>


</html>

templates/friends.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}
<div class="content-area">
    <div class="friend-card">        
        <span class="fs-5">{{ num_friends }} người bạn</span>
        <div class="accordion-collapse collapse show friend-tab-detail" id="listFriend" data-bs-parent="#friend-tab">
            <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
              {% for friend in friends %}                  
                <a href="{% url 'profiles:profile' friend.id   %}" class="friend-list-item d-flex align-items-center">
                  {% for profile in profiles %}               
                        {% if friend.id == profile.user.id %}
                            {% if profile.profile_pic %}
                                    <img src="{{ profile.profile_pic.url }}" style="width: 50px;" class="rounded-pill" alt="">
                                {% else %}
                                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDJaEoQJ0PLbNOn_xHRIw7mcyuIOj0_hVZlA&usqp=CAU" style="width: 50px;" style="width: 40px; height:40px" alt="">
                                {% endif %}
                        {% endif %}
                    {% endfor %}
                  <div class="name">{{ friend.username }}</div>                  
                </a>
              {% endfor %}                
            </div>
          </div>
       
    </div>

{% endblock %}